const ERROR_CODES = [
    { code: 0, message: "The card is added to main cards!" },
  { code: -100, message: "Empty parameters!" },
  { code: -101, message: "Error while executing the request, try again!" },
  { code: -102, message: "Error while executing the request, try again!" },
  { code: -103, message: "Checkout required fields!" },
  { code: -199, message: "JsonRpc ERROR" },
  { code: -200, message: "Card not found!" },
  { code: -201, message: "Card expired, capture card!" },
  { code: -202, message: "Pan invalid, wrong format!" },
  { code: -203, message: "Card not re-issue!" },
  { code: -204, message: "Card status is not active!" },
  { code: -205, message: "Card blocked!" },
  { code: -206, message: "SMS is not active!" },
  { code: -207, message: "Transaction already exists in the database!" },
  { code: -208, message: "Transaction not found!" },
  { code: -209, message: "Wrong format!" },
  { code: -210, message: "Transfer between the same cards not possible!" },
  { code: -211, message: "Server is not responding, try again later!" },
  { code: -212, message: "Pan or expiry invalid, wrong format!" },
  { code: -213, message: "Card numbers are the same!" },
  { code: -214, message: "Invalid date! Date must not be less than or equal to the current!" },
  { code: -215, message: "Pan and phone not found!" },
  { code: -216, message: "Expiration date incorrect!" },
  { code: -217, message: "Wrong phone number format!" },
  { code: -218, message: "The length of the card number must be 6 digits!" },
  { code: -219, message: "The card has already entered to main cards!" },
  { code: -220, message: "The card is added to main cards!" },
  { code: -221, message: "The card is not main!" },
  { code: -222, message: "OLD and NEW main cards are not in the same account!" },
  { code: -223, message: "OLD_MAIN does not exist!" },
  { code: -224, message: "Phone numbers are not same!" },
  { code: -225, message: "NEW_MAIN is expired!" },
  { code: -226, message: "NEW_MAIN does not exist!" },
  { code: -227, message: "OLD_MAIN does not exist!" },
  { code: -228, message: "Limit not found!" },
  { code: -229, message: "Family card error!" },
  { code: -230, message: "Can not set limit to main card!" },
  { code: -231, message: "Main card error!" },
  { code: -232, message: "There are no main cards in this account!" },
  { code: -233, message: "There is other main card in this account!" },
  { code: -234, message: "This card is main!" },
  { code: -235, message: "Supported card not found!" },
  { code: -236, message: "Supported terminal not found!" },
  { code: -237, message: "Merchant not found!" },
  { code: -238, message: "Account not found!" },
  { code: -239, message: "Improper funds for holding!" },
  { code: -240, message: "Insufficient funds!" },
  { code: -241, message: "Wrong period for holding!" },
  { code: -242, message: "Hold not found!" },
  { code: -243, message: "Device not found!" },
  { code: -244, message: "Service is temporarily unavailable for this bank!" },
  { code: -245, message: "Amount does not fit!" },
  { code: -246, message: "Payment to this provider is prohibited!" },
  { code: -247, message: "EPOS does not exist!" },
  { code: -248, message: "Card valid!" },
  { code: -249, message: "Terminal Id and Merchant Id already exist in the database!" },
  { code: -250, message: "Wrong Terminal type!" },
  { code: -251, message: "Wrong format Terminal Id!" },
  { code: -252, message: "Wrong format Merchant Id!" },
  { code: -253, message: "Terminal Id and Merchant Id not found in SV!" },
  { code: -254, message: "Terminal Id and Merchant Id not found in the database!" },
  { code: -255, message: "Terminal Id and Merchant Id not registered!" },
  { code: -256, message: "You do not have access to the method!" },
  { code: -257, message: "Token not found!" },
  { code: -258, message: "Operation is not possible with corporate cards!" },
  { code: -259, message: "The amountCredit should not exceed the amount!" },
  { code: -260, message: "Insufficient funds – retry" },
  { code: -261, message: "Card was blocked in SVGate! Will be unblocked in" },
  { code: -262, message: "Allowed amount exceeded!" },
  { code: -263, message: "StatusId should be between 0-21!" },
  { code: -264, message: "MCC code not found!" },
  { code: -265, message: "UNKNOWN EXCEPTION IN PACKAGE" },
  { code: -266, message: "SMS is already activated!" },
  { code: -267, message: "Transaction not found in SV!" },
  { code: -268, message: "EPOS is not authorized!" },
  { code: -269, message: "OTP is not correct!" },
  { code: -270, message: "OTP has expired!" },
  { code: -271, message: "Token already exists!" },
  { code: -272, message: "You do not have access to the status!" },
  { code: -273, message: "You do not have access to receive card information!" },
  { code: -274, message: "You do not have access to change card status" },
  { code: -275, message: "The card does not belong to your bank, you cannot change the status of the card!" },
  { code: -276, message: "The card does not belong to your bank!" },
  { code: -277, message: "The number attached to the card and the send number do not match!" },
  { code: -278, message: "SMS informing is already active!" },
  { code: -279, message: "The card is not main!" },
  { code: -280, message: "Information not found!" },
  { code: -281, message: "Error while executing the request, try again!" },
  { code: -282, message: "Transaction not found or transaction was canceled!" },
  { code: -283, message: "ATTO PAY Exception!" },
  { code: -284, message: "ATTO Check Card Exception!" },
  { code: -285, message: "ATTO Card not found!" },
  { code: -286, message: "EPOS not found!" },
  { code: -287, message: "User not found!" },
  { code: -288, message: "Actions not found!" },
  { code: -289, message: "Card not blocked!" },
  { code: -290, message: "Phone invalid, wrong format!" },
  { code: -291, message: "Access denied!" },
  { code: -292, message: "Error sending SMS, try again later!" },
  { code: -293, message: "Daily pin reset limit used!" },
  { code: -294, message: "Request OTP not found!" },
  { code: -295, message: "You do not have access to a SMS-notification activation!" },
  { code: -296, message: "The card does not belong to your bank, you cannot activate SMS-notification!" },
  { code: -297, message: "Phone is not correct!" },
  { code: -298, message: "This is not an EPOS, this is a POS!" },
  { code: -299, message: "SMS message not found!" },
  { code: -300, message: "Service not available, try again later!" },
  { code: -301, message: "Check out the trans.ext method later!" },
  { code: -302, message: "Check out the trans.ext method later!" },
  { code: -303, message: "Service not available, try again later!" },
  { code: -304, message: "Service not available, try again later!" },
  { code: -305, message: "Service not available, try again later!" },
  { code: -306, message: "Service not available, try again later!" },
  { code: -307, message: "Time out SV!" },
  { code: -308, message: "Check out the trans.ext method later!" },
  { code: -309, message: "Check out the trans.ext method later!" },
  { code: -310, message: "Check out the trans.ext method later!" },
  { code: -311, message: "Check out the trans.ext method later!" },
  { code: -314, message: "Bad OTP request ID, try new OTP!" },
  { code: -316, message: "Terminal no access to payment methods!" },
  { code: -318, message: "Type terminal debit is not selected at the time of registration!" },
  { code: -319, message: "Contact the administrator to obtain permission!" },
  { code: -320, message: "The phone number attached to the card and the requesting phone number do not match!" },
  { code: -321, message: "KEY is not correct!" },
  { code: -322, message: "KEY not found!" },
  { code: -323, message: "You do not have access to this limit!" },
  { code: -324, message: "LimitId is already set for this card!" },
  { code: -325, message: "Invalid date format!" },
  { code: -326, message: "LimitId is not set for this card!" },
  { code: -327, message: "The card does not belong to your bank, you cannot set a limit for this card!" },
  { code: -328, message: "The card does not belong to your bank, you cannot remove a limit for this card!" },
  { code: -329, message: "Wrong format parameter Date12!" },
  { code: -330, message: "Wrong format parameter Stan!" },
  { code: -333, message: "Errors from fraud monitoring(804! (UzKard))" },
  { code: -350, message: "Service not available, try again later (WCard)!" },
  { code: -351, message: "Service not available, try again later (WCard)!" },
  { code: -352, message: "Service not available, try again later (WCard)!" },
  { code: -353, message: "Service not available, try again later (WCard)!" },
  { code: -354, message: "Service not available, try again later (WCard)!" },
  { code: -355, message: "Service not available, try again later (WCard)!" },
  { code: -356, message: "Service not available, try again later (WCard)!" },
  { code: -357, message: "Service not available, try again later (WCard)!" },
  { code: -370, message: "You do not have a monitoring contract!" },
  { code: -371, message: "Card already exists in the database!" },
  { code: -372, message: "History token not found!" },
  { code: -373, message: "Card not found in donate database!" },
  { code: -374, message: "EPOS not activated!" },
  { code: -375, message: "EPOS is already activated!" },
  { code: -376, message: "Phone number not entered!" },
  { code: -377, message: "Only tokens can be sent in this field!" },
  { code: -378, message: "Error while creating token, try again later!" },
  { code: -379, message: "You can send no more than 5 tokens!" },
  { code: -380, message: "Transaction successful, if you want to reverse send to trans.reverse method!" },
  { code: -381, message: "Exceeds the base amount!" },
  { code: -382, message: "BIN not found!" },
  { code: -383, message: "You cannot work with this issuer!" },
  { code: -384, message: "All fields are not filled!" },
  { code: -385, message: "Format Date of Birth is not correct!" },
  { code: -386, message: "Format document expiration date is not correct!" },
  { code: -387, message: "EPOS not authorized for p2p.universal method!" },
  { code: -388, message: "Merchant and credit card do not belong to the same institution!" },
  { code: -389, message: "Repeated reverse transaction!" },
  { code: -390, message: "Code not found!" },
  { code: -392, message: "Card does not belong to this PINFL!" },
  { code: -393, message: "PINFL not found!" },
  { code: -398, message: "Token created for replenishment only!" },
  { code: -399, message: "WCard errors!" }
];

function getErrorMessage(code) {
    if (code >= -604 && code <= -400) {
        return "Service not available, try again later!";
    }
    const error = ERROR_CODES.find(err => err.code === code);
    return error ? error.message : "Unknown error!";
}

module.exports = { ERROR_CODES, getErrorMessage };